language: node_js
node_js:
  - stable
  - '--lts'
before_script:
  - npm run lint
  - npm run setup
  - npm run build
deploy:
  provider: script
  edge: true
  cleanup: false
  script:
    - npx semantic-release
  on:
    branch: master
    node_js: '--lts'
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
env:
  global:
    - secure: kIKCzhNMoC80mZYvrIaBZkL3+55emhm/2S4d571DnMu5GZ+o53e9ooUw1KWE+xMtoPzGFEdh6G2Z2Eon/hbn4r5pD/ens4mSqS4zv6A5dxgJdRN4DaTt5mo4gSr1DblDAy6UXDExEgTCAAliLnP8NlS+z1al5XBo5z7GvdD/tb0YEOu+MO/OgIOtznUe5JK9VzyB5ocf/k3R9ZnBeXlH2z5IcCHlcz4qtBn3K78Fi2B12s3Djya/wUID+cXms9xkcMHYW6AKrSbGIPbPVNZcnkNtgwpiLZ99LHbYRM/e5FWdvoAf5PCl8eh90e45WpmwiytYd2CqN067zRvw5Ay60LKfAOQ9PfsB0zK/+cL0ivYKSEe/ZyVqrcCGnjZQ3bH3EKDnYzOAOg7TKxsfqYEauXD+GWi6X8sUBUgTUx6Do0qEFNvsoX+zSRXyCvl+/CuFqkMG/SBwbCI9SHIbriHinjzaOwCU339fS92VE5XZP3A4CMMSLwqE0hgqB/rW7P1YuU6Wiqf7cEQONsyp5jywFx8XRZcJ4QB81IfweUanvq9l7m+kzJZGozGJ9rYD9XYP4AYnlqEQDtkk//YLsJCA0ffaz5xWzrx6gVYtTcBj0tMvg/h6NiZB6HILAfBmITSfr5wnGIoFthRcpWrFoMJZewJbHPOLKBYHs9ItUkQa03o=
    - secure: mZkJ0xm2U2eEB5ATE9UDO/Yd8E6B9MpwrfRv1y0WZQqKLjvrd3S2K0BWs7Z+Mdd9CXYqdjxV1r+X2GMnsIrQqolmIuGx0fbJHyZpXjMSaujrFl+HfWyBwiBK2dJuKwXPRE9jw2TqjWMqGRxvcpn6rBZj0myEVGYWsY1q/Hu3DQcs2bf5jHp+Cen00U3yT0Sg1M5y76FYHYGnCyJ42BFNta7VdjNHTaizTezjJzxuDuyDIF9lZfNhIKH7nJBYFxZp6vEjRznNXjJRTL0tCR9PrwDhH0zi+lqLUv7mlNrhjo2rxpIV5vVtxiqauP1iwvifD186iTZeDuXeV6ZatS745gQPqCmf3cWd8JbQSejo9JG0mT1vRw9gap1LKWnHAH5Ku3LAXKFUxVB7VKDQc13zFTIR2vA9Blrfhs42OxTmYSIg5nWwb6XK99yy/bmYRo3kswzzLc8UID6h6ALw3aaPr2nAW4QbVOkq7Wh9rOorfr2Ja6aleDR3F9sb8nT7m1WGCdnOECk4OhLQACGWEc4q8aR8ML/6Nv3O0vQiU4NxBwrXCT5LfgF+/PGP+c9VmNiUJdQH7RBsbyVWYWQCBW2+y4NmfwNKK8bCeOBRGqmMXQMoAST9m1kxq/NMCbjoFe+Se20TpVMQZdDsvqVAkJYD1CF1DF2HHcYyuJSzckg81xQ=
