language: node_js
node_js:
  - stable
  - '--lts'
before_script:
  - npm run setup
  - npm run build
deploy:
  provider: npm
  edge: true
  email: jaissatai6@gmail.com
  skip_cleanup: true
  api_key:
    secure: r7ehMC001sL+KG3Fs0kqQHhZxvmn3huumpcgbLnkv9gscT/5Dt221UsZdZgMFpTnzW+HgVUcvg1Xzte1L2T0WS4m/1cDzD+Bd80lToaTbdTIotFoffT1kN1yoWuoYN/gkZtup7XpyR2RD2I/kLybhn0D6XvEPCwN2gaoVPKQp5kafe79zTcpoSaDJysmGDo5T1S5s8+pMFSOnuwf8dLGPkDa+/L21kraQCEM5yV7aWyZQnzBYBwLg5UCbTQhqS60c0qaDMdODozNvFvPbCZeJUVd7D9EaAo5dBDd2WQXtXNCRGSCsCQtcDgmieU1CHNR0FSMcdMcJhJDkketJKZoGmjIy1yv7ZuTNSzvsNnPh+Bx8yQNlrCmg/mBCnh3rLXvOxLSe1VhnTWA+/1kmMx96I++gkFWNucEsLL1pemDaPzn2E+PlMHpqR5mYCHK92S0trNq/0KjD7qlG/xQvOBURJ5WXA17/yZPXlKEjPA2MN5W3icWCORK8q+2OSCqrm0J2mPtiVvuNs+PRcvRiOLP6n6JWWwu9bjIrIkAX269N7ubmVl6yQrPiN+QrkApWyfWioBfg7V1E08LBElcVtdAG2DMCS80YR3WFxBNidgxs7ENtnjXIFd7EgxQ0WZ1mfbps/KdyslLnWhWGdTWK+ioP4/RJHcl0Ei+moRQcsHQkxM=
  on:
    branch: master
    node_js: '--lts'
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
