language: node_js
node_js:
  - stable
  - '--lts'
before_script:
  - npm run lint
  - npm run setup
  - npm run build
deploy:
  provider: script
  edge: true
  cleanup: false
  script:
    - npx semantic-release
  on:
    branch: master
    node_js: '--lts'
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
env:
  global:
    - secure: LYzoY1QyAS4sMhnGk37+/60T0BcVeedZQaQ5AeLhOvn93YYFYoWOyOkGj/f1Lu9zpoScSrbd8gvEjS76yfq//Ax7H1LBnwwsO/jUY2YYIONS4MhtlNU6mOF0GN+E29y4kDyzE7kN3n1IB8xYZ4fmprAIJGykdcjxy07SaBOVS4HetpbgwPfcBcYzPbrRrb1v7p1jC2mQ0d4S9E2kfBUT8dllMLufxm9FYwVKDsJBS4JBFBPsYJ2Lyxpl+TGyobm1JOBs4dNaLOHV/c76MPNGaZl1ORJ3VLeIUPgGyTtOuM+PywMl16F3hqgWiVwMqDNV/ibapYHNgLeFfPhzrIWvLqTHFbGcJuJRWXB05IobVE9zcT5nnF2ugQXo/tB30WtzEX1cVK0Ip3n6K4gxB4Q3v8NCtyiTLCkB7/JUc8qi1YM3PDOPRsil3iac8tFykKGurlTcrI87rI6sBDgaDA6yz74pf2Hsx0wD2ZIlX9QbSnQ17woWCKdBp2aCmi3O2+nR7paBSIxpDsBlux0siJS5JuCN0I+qiJSyCuJwcKQxeXXSpbTAZHZxN9Adw7N+ga6J0FgP8kHHj7C5cihsjaekIrJt6NOrCq4ewblO0sAo/BHHE4p6BG7G3N3Sc3v8B0bQp3DPenyZ4yu9cY8uBIHox335ax9l8S5Xc3EeJWJZzwI=
    - secure: kF0L+pRtuPlzp512UnISOGeQeKnNosFc4XSzna5APQOSJXAhbq2SkRTFd0J3c2Q0AQzqEOYkhcuzUY9dEeh8KEwERuGm0T2PlS8jnpgqeJxCjnfa1GJLu3asD/X5gIIzcRrJtobb9A4MHywkwIwZyyuxblVScWd186GhnWHqB2s6vCd3sqmHeMTXwBuwOULkBVmFtiZAM6CiyltzWjdIglW5ehW299F4CHcHeXirzdn4zELwmXGeNVYg/sVHVCUdLKrtlAFa7+X4p49qKpCoU64RDqcY/yW59gZ8FfIMECaVyY+4VE3WbRO0jzkyOsZqOD8lFQ2qsXYFpb3scBbcjD/Vn/pYoYOqziYyW83Od00sC+K9Nw4BD5tCsHHXWXBpDIeTU5eGJzRw5eUBxwo9MGnvi4Pg2mN/XpegX59uxo752gW1SpZHtI3m9bOEBtdVrwycmiv6roYcM6gDsb8NTZdVslRrGVh21YU8nCuQsvt7D9drtuEPtEXiWlCRzeAM08YcpqOYbDmK+ypyltoMsey8KGDU60bh+tNzr9+D1yCm8lPVgpnPb3yZmVIWhj566X0OFiPT0hdfcWDVrHF+vUdflCaT5bZ3eAsMv0Fc3q1EcqE9PKFbPQa3gzGfr3jFsEtUK1FsevDgdMbpWEHqsI40zhD7bHSKwosdZOX7U3Q=
